=== cbosdo/coooder/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *   LibreOffice extension for syntax highlighting
 *   Copyright (C) 2008  CÃ©dric Bosdonnat cedric.bosdonnat.ooo@free.fr
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Library General Public
 *   License as published by the Free Software Foundation; 
 *   version 2 of the License.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Library General Public License for more details.
 *
 *   You should have received a copy of the GNU Library General Public
 *   License along with this library; if not, write to the Free
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 -->
<xsd:schema targetNamespace="http://cedric.bosdonnat.free.fr/coooder/language/" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://cedric.bosdonnat.free.fr/coooder/language/">

    <xsd:complexType name="LanguageType">
    	<xsd:sequence>
    		<xsd:element name="objectSplitters" type="SplittersType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="comments" type="CommentsType"></xsd:element>
    		<xsd:element name="symbols" type="SetType"></xsd:element>
    		<xsd:element name="quotemarks" type="ValuesType"></xsd:element>
    		<xsd:element name="hardquotes" type="ValuesType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="hardquoteEscapes" type="ValuesType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="keywords" type="SetType"></xsd:element>
    		<xsd:element name="regexps" type="RegexpsType"></xsd:element>
    		<xsd:element name="styles" type="StylesType"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="escapeChar" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="objectOriented" type="xsd:boolean" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="language" type="LanguageType"></xsd:element>

    <xsd:complexType name="CommentType" abstract="true">
    	<xsd:sequence>
    		<xsd:element name="opening" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SingleCommentType">
    	<xsd:complexContent>
    		<xsd:extension base="CommentType">
    			<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="MultipleCommentType">
    	<xsd:complexContent>
    		<xsd:extension base="CommentType">
    			<xsd:sequence>
    				<xsd:element name="closing" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    			</xsd:sequence>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="CommentsType">
    	<xsd:sequence>
    		<xsd:element name="single" type="SingleCommentType"
    			minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    		<xsd:element name="multiple" type="MultipleCommentType"
    			minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="caseSensitive" type="xsd:boolean" use="optional" default="true"></xsd:attribute>
    </xsd:complexType>
    

    <xsd:complexType name="ValuesType">
    	<xsd:sequence>
    		<xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SplittersType">
    	<xsd:sequence>
    		<xsd:element name="splitter" type="SplitterType" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SplitterType">
		<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="SetType">
    	<xsd:sequence>
    		<xsd:element name="set" type="SetElementsType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="SetElementsType">
    	<xsd:sequence>
    		<xsd:element name="value" type="xsd:string" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    	<xsd:attribute name="caseSensitive" type="xsd:boolean" default="true" use="optional"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="RegexpsType">
    	<xsd:sequence>
    		<xsd:element name="regexp" type="RegexpType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>



    <xsd:complexType name="RegexpType">
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    	<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

	<xsd:complexType name="StylesType">
		<xsd:sequence>

			<xsd:element name="style" type="StyleType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	

	<xsd:simpleType name="IdStyleType">
		<xsd:union memberTypes="xsd:IDREF ">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="comment_multi" />
					<xsd:enumeration value="string" />
					<xsd:enumeration value="escaped" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="symbol" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>

    <xsd:complexType name="StyleType">
    	<xsd:attribute name="element" type="IdStyleType"></xsd:attribute>
    	<xsd:attribute name="color" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="bold" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
    	<xsd:attribute name="italic" type="xsd:boolean"  use="optional" default="false"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== cbosdo/coooder/config/org/libreoffice/langs/ocaml.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="ocaml" name="OCaml" objectOriented="true" escapeChar=""><l:objectSplitters><l:splitter id="splitter_1" value="."/></l:objectSplitters><l:comments caseSensitive="false"><l:multiple><l:opening>(*</l:opening><l:closing>*)</l:closing></l:multiple></l:comments><l:symbols><l:set id="symbols_0"><l:value>;</l:value><l:value>!</l:value><l:value>:</l:value><l:value>.</l:value><l:value>=</l:value><l:value>%</l:value><l:value>^</l:value><l:value>*</l:value><l:value>-</l:value><l:value>/</l:value><l:value>+</l:value><l:value>&gt;</l:value><l:value>&lt;</l:value><l:value>(</l:value><l:value>)</l:value><l:value>[</l:value><l:value>]</l:value><l:value>&amp;</l:value><l:value>|</l:value><l:value>#</l:value><l:value>'</l:value></l:set></l:symbols><l:quotemarks><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>and</l:value><l:value>as</l:value><l:value>asr</l:value><l:value>begin</l:value><l:value>class</l:value><l:value>closed</l:value><l:value>constraint</l:value><l:value>do</l:value><l:value>done</l:value><l:value>downto</l:value><l:value>else</l:value><l:value>end</l:value><l:value>exception</l:value><l:value>external</l:value><l:value>failwith</l:value><l:value>false</l:value><l:value>flush</l:value><l:value>for</l:value><l:value>fun</l:value><l:value>function</l:value><l:value>functor</l:value><l:value>if</l:value><l:value>in</l:value><l:value>include</l:value><l:value>inherit</l:value><l:value>incr</l:value><l:value>land</l:value><l:value>let</l:value><l:value>load</l:value><l:value>los</l:value><l:value>lsl</l:value><l:value>lsr</l:value><l:value>lxor</l:value><l:value>match</l:value><l:value>method</l:value><l:value>mod</l:value><l:value>module</l:value><l:value>mutable</l:value><l:value>new</l:value><l:value>not</l:value><l:value>of</l:value><l:value>open</l:value><l:value>option</l:value><l:value>or</l:value><l:value>parser</l:value><l:value>private</l:value><l:value>ref</l:value><l:value>rec</l:value><l:value>raise</l:value><l:value>regexp</l:value><l:value>sig</l:value><l:value>struct</l:value><l:value>stdout</l:value><l:value>stdin</l:value><l:value>stderr</l:value><l:value>then</l:value><l:value>to</l:value><l:value>true</l:value><l:value>try</l:value><l:value>type</l:value><l:value>val</l:value><l:value>virtual</l:value><l:value>when</l:value><l:value>while</l:value><l:value>with</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>Arg</l:value><l:value>Arith_status</l:value><l:value>Array</l:value><l:value>ArrayLabels</l:value><l:value>Big_int</l:value><l:value>Bigarray</l:value><l:value>Buffer</l:value><l:value>Callback</l:value><l:value>CamlinternalOO</l:value><l:value>Char</l:value><l:value>Complex</l:value><l:value>Condition</l:value><l:value>Dbm</l:value><l:value>Digest</l:value><l:value>Dynlink</l:value><l:value>Event</l:value><l:value>Filename</l:value><l:value>Format</l:value><l:value>Gc</l:value><l:value>Genlex</l:value><l:value>Graphics</l:value><l:value>GraphicsX11</l:value><l:value>Hashtbl</l:value><l:value>Int32</l:value><l:value>Int64</l:value><l:value>Lazy</l:value><l:value>Lexing</l:value><l:value>List</l:value><l:value>ListLabels</l:value><l:value>Map</l:value><l:value>Marshal</l:value><l:value>MoreLabels</l:value><l:value>Mutex</l:value><l:value>Nativeint</l:value><l:value>Num</l:value><l:value>Obj</l:value><l:value>Oo</l:value><l:value>Parsing</l:value><l:value>Pervasives</l:value><l:value>Printexc</l:value><l:value>Printf</l:value><l:value>Queue</l:value><l:value>Random</l:value><l:value>Scanf</l:value><l:value>Set</l:value><l:value>Sort</l:value><l:value>Stack</l:value><l:value>StdLabels</l:value><l:value>Str</l:value><l:value>Stream</l:value><l:value>String</l:value><l:value>StringLabels</l:value><l:value>Sys</l:value><l:value>Thread</l:value><l:value>ThreadUnix</l:value><l:value>Tk</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>raise</l:value><l:value>invalid_arg</l:value><l:value>failwith</l:value><l:value>compare</l:value><l:value>min</l:value><l:value>max</l:value><l:value>succ</l:value><l:value>pred</l:value><l:value>mod</l:value><l:value>abs</l:value><l:value>max_int</l:value><l:value>min_int</l:value><l:value>sqrt</l:value><l:value>exp</l:value><l:value>log</l:value><l:value>log10</l:value><l:value>cos</l:value><l:value>sin</l:value><l:value>tan</l:value><l:value>acos</l:value><l:value>asin</l:value><l:value>atan</l:value><l:value>atan2</l:value><l:value>cosh</l:value><l:value>sinh</l:value><l:value>tanh</l:value><l:value>ceil</l:value><l:value>floor</l:value><l:value>abs_float</l:value><l:value>mod_float</l:value><l:value>frexp</l:value><l:value>ldexp</l:value><l:value>modf</l:value><l:value>float</l:value><l:value>float_of_int</l:value><l:value>truncate</l:value><l:value>int_of_float</l:value><l:value>infinity</l:value><l:value>nan</l:value><l:value>max_float</l:value><l:value>min_float</l:value><l:value>epsilon_float</l:value><l:value>classify_float</l:value><l:value>int_of_char</l:value><l:value>char_of_int</l:value><l:value>ignore</l:value><l:value>string_of_bool</l:value><l:value>bool_of_string</l:value><l:value>string_of_int</l:value><l:value>int_of_string</l:value><l:value>string_of_float</l:value><l:value>float_of_string</l:value><l:value>fst</l:value><l:value>snd</l:value><l:value>stdin</l:value><l:value>stdout</l:value><l:value>stderr</l:value><l:value>print_char</l:value><l:value>print_string</l:value><l:value>print_int</l:value><l:value>print_float</l:value><l:value>print_endline</l:value><l:value>print_newline</l:value><l:value>prerr_char</l:value><l:value>prerr_string</l:value><l:value>prerr_int</l:value><l:value>prerr_float</l:value><l:value>prerr_endline</l:value><l:value>prerr_newline</l:value><l:value>read_line</l:value><l:value>read_int</l:value><l:value>read_float</l:value><l:value>open_out</l:value><l:value>open_out_bin</l:value><l:value>open_out_gen</l:value><l:value>flush</l:value><l:value>flush_all</l:value><l:value>output_char</l:value><l:value>output_string</l:value><l:value>output</l:value><l:value>output_byte</l:value><l:value>output_binary_int</l:value><l:value>output_value</l:value><l:value>seek_out</l:value><l:value>pos_out</l:value><l:value>out_channel_length</l:value><l:value>close_out</l:value><l:value>close_out_noerr</l:value><l:value>set_binary_mode_out</l:value><l:value>open_in</l:value><l:value>open_in_bin</l:value><l:value>open_in_gen</l:value><l:value>input_char</l:value><l:value>input_line</l:value><l:value>input</l:value><l:value>really_input</l:value><l:value>input_byte</l:value><l:value>input_binary_int</l:value><l:value>input_value</l:value><l:value>seek_in</l:value><l:value>pos_in</l:value><l:value>in_channel_length</l:value><l:value>close_in</l:value><l:value>close_in_noerr</l:value><l:value>set_binary_mode_in</l:value><l:value>incr</l:value><l:value>decr</l:value><l:value>string_of_format</l:value><l:value>format_of_string</l:value><l:value>exit</l:value><l:value>at_exit</l:value></l:set><l:set id="keywords_4" caseSensitive="false"><l:value>fpclass</l:value><l:value>in_channel</l:value><l:value>out_channel</l:value><l:value>open_flag</l:value><l:value>Sys_error</l:value><l:value>ref</l:value><l:value>format</l:value></l:set><l:set id="keywords_5" caseSensitive="false"><l:value>Exit</l:value><l:value>Invalid_Argument</l:value><l:value>Failure</l:value><l:value>Division_by_zero</l:value></l:set></l:keywords><l:regexps></l:regexps><l:styles><l:style element="splitter_1" color="060"/><l:style element="symbols_0" color="a52a2a"/><l:style element="keywords_1" color="06c" bold="true"/><l:style element="keywords_2" color="06c" bold="true"/><l:style element="keywords_3" color="06c" bold="true"/><l:style element="keywords_4" color="06c" bold="true"/><l:style element="keywords_5" color="06c" bold="true"/><l:style element="comment_multi" color="5d478b" italic="true"/><l:style element="string" color="3cb371"/><l:style element="number" color="c6c"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/applescript.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="applescript" name="AppleScript" objectOriented="true" escapeChar="\"><l:objectSplitters><l:splitter id="splitter_1" value=",+-=&amp;lt;&amp;gt;/?^&amp;amp;*"/></l:objectSplitters><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>--</l:opening></l:single><l:multiple><l:opening>(*</l:opening><l:closing>*)</l:closing></l:multiple></l:comments><l:symbols><l:set id="symbols_0"><l:value>)</l:value><l:value>+</l:value><l:value>-</l:value><l:value>^</l:value><l:value>*</l:value><l:value>/</l:value><l:value>&amp;</l:value><l:value>&lt;</l:value><l:value>&gt;=</l:value><l:value>&lt;</l:value><l:value>&lt;=</l:value><l:value>=</l:value><l:value>&iuml;&iquest;&frac12;</l:value></l:set></l:symbols><l:quotemarks><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>script</l:value><l:value>property</l:value><l:value>prop</l:value><l:value>end</l:value><l:value>to</l:value><l:value>set</l:value><l:value>global</l:value><l:value>local</l:value><l:value>on</l:value><l:value>of</l:value><l:value>in</l:value><l:value>given</l:value><l:value>with</l:value><l:value>without</l:value><l:value>return</l:value><l:value>continue</l:value><l:value>tell</l:value><l:value>if</l:value><l:value>then</l:value><l:value>else</l:value><l:value>repeat</l:value><l:value>times</l:value><l:value>while</l:value><l:value>until</l:value><l:value>from</l:value><l:value>exit</l:value><l:value>try</l:value><l:value>error</l:value><l:value>considering</l:value><l:value>ignoring</l:value><l:value>timeout</l:value><l:value>transaction</l:value><l:value>my</l:value><l:value>get</l:value><l:value>put</l:value><l:value>into</l:value><l:value>is</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>each</l:value><l:value>some</l:value><l:value>every</l:value><l:value>whose</l:value><l:value>where</l:value><l:value>id</l:value><l:value>index</l:value><l:value>first</l:value><l:value>second</l:value><l:value>third</l:value><l:value>fourth</l:value><l:value>fifth</l:value><l:value>sixth</l:value><l:value>seventh</l:value><l:value>eighth</l:value><l:value>ninth</l:value><l:value>tenth</l:value><l:value>last</l:value><l:value>front</l:value><l:value>back</l:value><l:value>st</l:value><l:value>nd</l:value><l:value>rd</l:value><l:value>th</l:value><l:value>middle</l:value><l:value>named</l:value><l:value>through</l:value><l:value>thru</l:value><l:value>before</l:value><l:value>after</l:value><l:value>beginning</l:value><l:value>the</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>close</l:value><l:value>copy</l:value><l:value>count</l:value><l:value>delete</l:value><l:value>duplicate</l:value><l:value>exists</l:value><l:value>launch</l:value><l:value>make</l:value><l:value>move</l:value><l:value>open</l:value><l:value>print</l:value><l:value>quit</l:value><l:value>reopen</l:value><l:value>run</l:value><l:value>save</l:value><l:value>saving</l:value><l:value>it</l:value><l:value>me</l:value><l:value>version</l:value><l:value>pi</l:value><l:value>result</l:value><l:value>space</l:value><l:value>tab</l:value><l:value>anything</l:value><l:value>case</l:value><l:value>diacriticals</l:value><l:value>expansion</l:value><l:value>hyphens</l:value><l:value>punctuation</l:value><l:value>bold</l:value><l:value>condensed</l:value><l:value>expanded</l:value><l:value>hidden</l:value><l:value>italic</l:value><l:value>outline</l:value><l:value>plain</l:value><l:value>shadow</l:value><l:value>strikethrough</l:value><l:value>subscript</l:value><l:value>superscript</l:value><l:value>underline</l:value><l:value>ask</l:value><l:value>no</l:value><l:value>yes</l:value><l:value>false</l:value><l:value>true</l:value><l:value>weekday</l:value><l:value>monday</l:value><l:value>mon</l:value><l:value>tuesday</l:value><l:value>tue</l:value><l:value>wednesday</l:value><l:value>wed</l:value><l:value>thursday</l:value><l:value>thu</l:value><l:value>friday</l:value><l:value>fri</l:value><l:value>saturday</l:value><l:value>sat</l:value><l:value>sunday</l:value><l:value>sun</l:value><l:value>month</l:value><l:value>january</l:value><l:value>jan</l:value><l:value>february</l:value><l:value>feb</l:value><l:value>march</l:value><l:value>mar</l:value><l:value>april</l:value><l:value>apr</l:value><l:value>may</l:value><l:value>june</l:value><l:value>jun</l:value><l:value>july</l:value><l:value>jul</l:value><l:value>august</l:value><l:value>aug</l:value><l:value>september</l:value><l:value>sep</l:value><l:value>october</l:value><l:value>oct</l:value><l:value>november</l:value><l:value>nov</l:value><l:value>december</l:value><l:value>dec</l:value><l:value>minutes</l:value><l:value>hours</l:value><l:value>days</l:value><l:value>weeks</l:value><l:value>div</l:value><l:value>mod</l:value><l:value>and</l:value><l:value>not</l:value><l:value>or</l:value><l:value>as</l:value><l:value>contains</l:value><l:value>equal</l:value><l:value>equals</l:value><l:value>isnt</l:value></l:set></l:keywords><l:regexps><l:regexp id="regexp_0" value="[\$%@]+[a-zA-Z_][a-zA-Z0-9_]*"/><l:regexp id="regexp_4" value="&amp;lt;[a-zA-Z_][a-zA-Z0-9_]*&amp;gt;"/></l:regexps><l:styles><l:style element="splitter_1" color="006600"/><l:style element="comments_1" color="808080" italic="true"/><l:style element="symbols_0" color="66cc66"/><l:style element="keywords_1" color="b1b100"/><l:style element="keywords_2" color="000000" bold="true"/><l:style element="keywords_3" color="000066"/><l:style element="regexp_0" color="0000ff"/><l:style element="regexp_4" color="009999"/><l:style element="comment_multi" color="808080" italic="true"/><l:style element="string" color="ff0000"/><l:style element="number" color="cc66cc"/><l:style element="escaped" color="000099" bold="true"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/smarty.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="smarty" name="Smarty" objectOriented="true" escapeChar="\"><l:objectSplitters><l:splitter id="splitter_1" value="."/></l:objectSplitters><l:comments caseSensitive="false"><l:multiple><l:opening>{*</l:opening><l:closing>*}</l:closing></l:multiple></l:comments><l:symbols><l:set id="symbols_0"><l:value>/</l:value><l:value>=</l:value><l:value>==</l:value><l:value>!=</l:value><l:value>&gt;</l:value><l:value>&lt;</l:value><l:value>&gt;=</l:value><l:value>&lt;=</l:value><l:value>!</l:value><l:value>%</l:value></l:set></l:symbols><l:quotemarks><l:value>'</l:value><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>$smarty</l:value><l:value>now</l:value><l:value>const</l:value><l:value>capture</l:value><l:value>config</l:value><l:value>section</l:value><l:value>foreach</l:value><l:value>template</l:value><l:value>version</l:value><l:value>ldelim</l:value><l:value>rdelim</l:value><l:value>config_load</l:value><l:value>foreachelse</l:value><l:value>include</l:value><l:value>include_php</l:value><l:value>insert</l:value><l:value>if</l:value><l:value>elseif</l:value><l:value>else</l:value><l:value>php</l:value><l:value>sectionelse</l:value><l:value>clear_all_cache</l:value><l:value>clear_cache</l:value><l:value>is_cached</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>capitalize</l:value><l:value>count_characters</l:value><l:value>cat</l:value><l:value>count_paragraphs</l:value><l:value>count_sentences</l:value><l:value>count_words</l:value><l:value>date_format</l:value><l:value>default</l:value><l:value>escape</l:value><l:value>indent</l:value><l:value>lower</l:value><l:value>nl2br</l:value><l:value>regex_replace</l:value><l:value>replace</l:value><l:value>spacify</l:value><l:value>string_format</l:value><l:value>strip</l:value><l:value>strip_tags</l:value><l:value>truncate</l:value><l:value>upper</l:value><l:value>wordwrap</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>assign</l:value><l:value>counter</l:value><l:value>cycle</l:value><l:value>debug</l:value><l:value>eval</l:value><l:value>fetch</l:value><l:value>html_checkboxes</l:value><l:value>html_image</l:value><l:value>html_options</l:value><l:value>html_radios</l:value><l:value>html_select_date</l:value><l:value>html_select_time</l:value><l:value>html_table</l:value><l:value>math</l:value><l:value>mailto</l:value><l:value>popup_init</l:value><l:value>popup</l:value><l:value>textformat</l:value></l:set><l:set id="keywords_4" caseSensitive="false"><l:value>$template_dir</l:value><l:value>$compile_dir</l:value><l:value>$config_dir</l:value><l:value>$plugins_dir</l:value><l:value>$debugging</l:value><l:value>$debug_tpl</l:value><l:value>$debugging_ctrl</l:value><l:value>$autoload_filters</l:value><l:value>$compile_check</l:value><l:value>$force_compile</l:value><l:value>$caching</l:value><l:value>$cache_dir</l:value><l:value>$cache_lifetime</l:value><l:value>$cache_handler_func</l:value><l:value>$cache_modified_check</l:value><l:value>$config_overwrite</l:value><l:value>$config_booleanize</l:value><l:value>$config_read_hidden</l:value><l:value>$config_fix_newlines</l:value><l:value>$default_template_handler_func</l:value><l:value>$php_handling</l:value><l:value>$security</l:value><l:value>$secure_dir</l:value><l:value>$security_settings</l:value><l:value>$trusted_dir</l:value><l:value>$left_delimiter</l:value><l:value>$right_delimiter</l:value><l:value>$compiler_class</l:value><l:value>$request_vars_order</l:value><l:value>$request_use_auto_globals</l:value><l:value>$error_reporting</l:value><l:value>$compile_id</l:value><l:value>$use_sub_dirs</l:value><l:value>$default_modifiers</l:value><l:value>$default_resource_type</l:value></l:set><l:set id="keywords_5" caseSensitive="false"><l:value>append</l:value><l:value>append_by_ref</l:value><l:value>assign</l:value><l:value>assign_by_ref</l:value><l:value>clear_all_assign</l:value><l:value>clear_all_cache</l:value><l:value>clear_assign</l:value><l:value>clear_cache</l:value><l:value>clear_compiled_tpl</l:value><l:value>clear_config</l:value><l:value>config_load</l:value><l:value>display</l:value><l:value>fetch</l:value><l:value>get_config_vars</l:value><l:value>get_registered_object</l:value><l:value>get_template_vars</l:value><l:value>is_cached</l:value><l:value>load_filter</l:value><l:value>register_block</l:value><l:value>register_compiler_function</l:value><l:value>register_function</l:value><l:value>register_modifier</l:value><l:value>register_object</l:value><l:value>register_outputfilter</l:value><l:value>register_postfilter</l:value><l:value>register_prefilter</l:value><l:value>register_resource</l:value><l:value>trigger_error</l:value><l:value>template_exists</l:value><l:value>unregister_block</l:value><l:value>unregister_compiler_function</l:value><l:value>unregister_function</l:value><l:value>unregister_modifier</l:value><l:value>unregister_object</l:value><l:value>unregister_outputfilter</l:value><l:value>unregister_postfilter</l:value><l:value>unregister_prefilter</l:value><l:value>unregister_resource</l:value></l:set><l:set id="keywords_6" caseSensitive="false"><l:value>name</l:value><l:value>assign</l:value><l:value>file</l:value><l:value>scope</l:value><l:value>global</l:value><l:value>key</l:value><l:value>once</l:value><l:value>script</l:value><l:value>loop</l:value><l:value>start</l:value><l:value>step</l:value><l:value>max</l:value><l:value>show</l:value><l:value>values</l:value><l:value>value</l:value><l:value>from</l:value><l:value>item</l:value></l:set><l:set id="keywords_7" caseSensitive="false"><l:value>eq</l:value><l:value>neq</l:value><l:value>ne</l:value><l:value>lte</l:value><l:value>gte</l:value><l:value>ge</l:value><l:value>le</l:value><l:value>not</l:value><l:value>mod</l:value></l:set><l:set id="keywords_8" caseSensitive="false"><l:value>isset</l:value><l:value>is_array</l:value><l:value>empty</l:value><l:value>count</l:value><l:value>sizeof</l:value></l:set></l:keywords><l:regexps><l:regexp id="regexp_0" value="\$[a-zA-Z][a-zA-Z0-9_]*"/></l:regexps><l:styles><l:style element="splitter_1" color="006600"/><l:style element="symbols_0" color="D36900"/><l:style element="keywords_1" color="0600FF"/><l:style element="keywords_2" color="008000"/><l:style element="keywords_3" color="0600FF"/><l:style element="keywords_4" color="804040"/><l:style element="keywords_5" color="008000"/><l:style element="keywords_6" color="6A0A0A"/><l:style element="keywords_7" color="D36900"/><l:style element="keywords_8" color="0600FF"/><l:style element="regexp_0" color="00aaff"/><l:style element="comment_multi" color="008080" italic="true"/><l:style element="string" color="ff0000"/><l:style element="number" color="cc66cc"/><l:style element="escaped" color="000099" bold="true"/></l:styles></l:language>
