=== cbosdo/coooder/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *   LibreOffice extension for syntax highlighting
 *   Copyright (C) 2008  CÃ©dric Bosdonnat cedric.bosdonnat.ooo@free.fr
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Library General Public
 *   License as published by the Free Software Foundation; 
 *   version 2 of the License.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Library General Public License for more details.
 *
 *   You should have received a copy of the GNU Library General Public
 *   License along with this library; if not, write to the Free
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 -->
<xsd:schema targetNamespace="http://cedric.bosdonnat.free.fr/coooder/language/" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://cedric.bosdonnat.free.fr/coooder/language/">

    <xsd:complexType name="LanguageType">
    	<xsd:sequence>
    		<xsd:element name="objectSplitters" type="SplittersType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="comments" type="CommentsType"></xsd:element>
    		<xsd:element name="symbols" type="SetType"></xsd:element>
    		<xsd:element name="quotemarks" type="ValuesType"></xsd:element>
    		<xsd:element name="hardquotes" type="ValuesType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="hardquoteEscapes" type="ValuesType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="keywords" type="SetType"></xsd:element>
    		<xsd:element name="regexps" type="RegexpsType"></xsd:element>
    		<xsd:element name="styles" type="StylesType"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="escapeChar" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="objectOriented" type="xsd:boolean" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="language" type="LanguageType"></xsd:element>

    <xsd:complexType name="CommentType" abstract="true">
    	<xsd:sequence>
    		<xsd:element name="opening" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SingleCommentType">
    	<xsd:complexContent>
    		<xsd:extension base="CommentType">
    			<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="MultipleCommentType">
    	<xsd:complexContent>
    		<xsd:extension base="CommentType">
    			<xsd:sequence>
    				<xsd:element name="closing" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    			</xsd:sequence>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="CommentsType">
    	<xsd:sequence>
    		<xsd:element name="single" type="SingleCommentType"
    			minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    		<xsd:element name="multiple" type="MultipleCommentType"
    			minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="caseSensitive" type="xsd:boolean" use="optional" default="true"></xsd:attribute>
    </xsd:complexType>
    

    <xsd:complexType name="ValuesType">
    	<xsd:sequence>
    		<xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SplittersType">
    	<xsd:sequence>
    		<xsd:element name="splitter" type="SplitterType" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SplitterType">
		<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="SetType">
    	<xsd:sequence>
    		<xsd:element name="set" type="SetElementsType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="SetElementsType">
    	<xsd:sequence>
    		<xsd:element name="value" type="xsd:string" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    	<xsd:attribute name="caseSensitive" type="xsd:boolean" default="true" use="optional"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="RegexpsType">
    	<xsd:sequence>
    		<xsd:element name="regexp" type="RegexpType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>



    <xsd:complexType name="RegexpType">
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    	<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

	<xsd:complexType name="StylesType">
		<xsd:sequence>

			<xsd:element name="style" type="StyleType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	

	<xsd:simpleType name="IdStyleType">
		<xsd:union memberTypes="xsd:IDREF ">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="comment_multi" />
					<xsd:enumeration value="string" />
					<xsd:enumeration value="escaped" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="symbol" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>

    <xsd:complexType name="StyleType">
    	<xsd:attribute name="element" type="IdStyleType"></xsd:attribute>
    	<xsd:attribute name="color" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="bold" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
    	<xsd:attribute name="italic" type="xsd:boolean"  use="optional" default="false"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== cbosdo/coooder/config/org/libreoffice/langs/xorg_conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="xorg_conf" name="Xorg configuration" objectOriented="false" escapeChar="\"><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>#</l:opening></l:single></l:comments><l:symbols></l:symbols><l:quotemarks><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>Section</l:value><l:value>EndSection</l:value><l:value>SubSection</l:value><l:value>EndSubSection</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>BiosBase</l:value><l:value>Black</l:value><l:value>Boardname</l:value><l:value>BusID</l:value><l:value>ChipID</l:value><l:value>ChipRev</l:value><l:value>Chipset</l:value><l:value>ClockChip</l:value><l:value>Clocks</l:value><l:value>DacSpeed</l:value><l:value>DefaultDepth</l:value><l:value>DefaultFbBpp</l:value><l:value>Depth</l:value><l:value>Device</l:value><l:value>DisplaySize</l:value><l:value>Driver</l:value><l:value>FbBpp</l:value><l:value>Gamma</l:value><l:value>HorizSync</l:value><l:value>IOBase</l:value><l:value>Identifier</l:value><l:value>InputDevice</l:value><l:value>Load</l:value><l:value>MemBase</l:value><l:value>Mode</l:value><l:value>Modeline</l:value><l:value>Modelname</l:value><l:value>Modes</l:value><l:value>Monitor</l:value><l:value>Option</l:value><l:value>Ramdac</l:value><l:value>RgbPath</l:value><l:value>Screen</l:value><l:value>TextClockFreq</l:value><l:value>UseModes</l:value><l:value>VendorName</l:value><l:value>VertRefresh</l:value><l:value>VideoAdaptor</l:value><l:value>VideoRam</l:value><l:value>ViewPort</l:value><l:value>Virtual</l:value><l:value>Visual</l:value><l:value>Weight</l:value><l:value>White</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>Above</l:value><l:value>Absolute</l:value><l:value>Below</l:value><l:value>LeftOf</l:value><l:value>Relative</l:value><l:value>RightOf</l:value><l:value>DotClock</l:value><l:value>Flags</l:value><l:value>HSkew</l:value><l:value>HTimings</l:value><l:value>VScan</l:value><l:value>VTimings</l:value></l:set></l:keywords><l:regexps></l:regexps><l:styles><l:style element="comments_1" color="adadad" italic="true"/><l:style element="keywords_1" color="b1b100"/><l:style element="keywords_2" color="990000"/><l:style element="keywords_3" color="550000"/><l:style element="string" color="0000ff"/><l:style element="number" color="cc66cc"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/eiffel.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="eiffel" name="Eiffel" objectOriented="true" escapeChar="%"><l:objectSplitters><l:splitter id="splitter_1" value="."/></l:objectSplitters><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>--</l:opening></l:single></l:comments><l:symbols><l:set id="symbols_0"><l:value>+</l:value><l:value>-</l:value><l:value>*</l:value><l:value>?</l:value><l:value>=</l:value><l:value>/</l:value><l:value>%</l:value><l:value>&amp;</l:value><l:value>&gt;</l:value><l:value>&lt;</l:value><l:value>^</l:value><l:value>!</l:value><l:value>|</l:value><l:value>:</l:value><l:value>(</l:value><l:value>)</l:value><l:value>{</l:value><l:value>}</l:value><l:value>[</l:value><l:value>]</l:value><l:value>#</l:value></l:set></l:symbols><l:quotemarks><l:value>'</l:value><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>separate</l:value><l:value>invariant</l:value><l:value>inherit</l:value><l:value>indexing</l:value><l:value>feature</l:value><l:value>expanded</l:value><l:value>deferred</l:value><l:value>class</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>xor</l:value><l:value>when</l:value><l:value>variant</l:value><l:value>until</l:value><l:value>unique</l:value><l:value>undefine</l:value><l:value>then</l:value><l:value>strip</l:value><l:value>select</l:value><l:value>retry</l:value><l:value>rescue</l:value><l:value>require</l:value><l:value>rename</l:value><l:value>reference</l:value><l:value>redefine</l:value><l:value>prefix</l:value><l:value>or</l:value><l:value>once</l:value><l:value>old</l:value><l:value>obsolete</l:value><l:value>not</l:value><l:value>loop</l:value><l:value>local</l:value><l:value>like</l:value><l:value>is</l:value><l:value>inspect</l:value><l:value>infix</l:value><l:value>include</l:value><l:value>implies</l:value><l:value>if</l:value><l:value>frozen</l:value><l:value>from</l:value><l:value>external</l:value><l:value>export</l:value><l:value>ensure</l:value><l:value>end</l:value><l:value>elseif</l:value><l:value>else</l:value><l:value>do</l:value><l:value>creation</l:value><l:value>create</l:value><l:value>check</l:value><l:value>as</l:value><l:value>and</l:value><l:value>alias</l:value><l:value>agent</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>Void</l:value><l:value>True</l:value><l:value>Result</l:value><l:value>Precursor</l:value><l:value>False</l:value><l:value>Current</l:value></l:set><l:set id="keywords_4" caseSensitive="false"><l:value>UNIX_SIGNALS</l:value><l:value>UNIX_FILE_INFO</l:value><l:value>UNBOUNDED</l:value><l:value>TWO_WAY_TREE_CURSOR</l:value><l:value>TWO_WAY_TREE</l:value><l:value>TWO_WAY_SORTED_SET</l:value><l:value>TWO_WAY_LIST</l:value><l:value>TWO_WAY_CURSOR_TREE</l:value><l:value>TWO_WAY_CIRCULAR</l:value><l:value>TWO_WAY_CHAIN_ITERATOR</l:value><l:value>TUPLE</l:value><l:value>TREE</l:value><l:value>TRAVERSABLE</l:value><l:value>TO_SPECIAL</l:value><l:value>THREAD_CONTROL</l:value><l:value>THREAD_ATTRIBUTES</l:value><l:value>THREAD</l:value><l:value>TABLE</l:value><l:value>SUBSET</l:value><l:value>STRING_HANDLER</l:value><l:value>STRING</l:value><l:value>STREAM</l:value><l:value>STORABLE</l:value><l:value>STD_FILES</l:value><l:value>STACK</l:value><l:value>SPECIAL</l:value><l:value>SORTED_TWO_WAY_LIST</l:value><l:value>SORTED_STRUCT</l:value><l:value>SORTED_LIST</l:value><l:value>SINGLE_MATH</l:value><l:value>SET</l:value><l:value>SEQUENCE</l:value><l:value>SEQ_STRING</l:value><l:value>SEMAPHORE</l:value><l:value>ROUTINE</l:value><l:value>RESIZABLE</l:value><l:value>RECURSIVE_TREE_CURSOR</l:value><l:value>RECURSIVE_CURSOR_TREE</l:value><l:value>REAL_REF</l:value><l:value>REAL</l:value><l:value>RAW_FILE</l:value><l:value>RANDOM</l:value><l:value>QUEUE</l:value><l:value>PROXY</l:value><l:value>PROFILING_SETTING</l:value><l:value>PROCEDURE</l:value><l:value>PRIORITY_QUEUE</l:value><l:value>PRIMES</l:value><l:value>PRECOMP</l:value><l:value>POINTER_REF</l:value><l:value>POINTER</l:value><l:value>PLATFORM</l:value><l:value>PLAIN_TEXT_FILE</l:value><l:value>PATH_NAME</l:value><l:value>PART_SORTED_TWO_WAY_LIST</l:value><l:value>PART_SORTED_SET</l:value><l:value>PART_SORTED_LIST</l:value><l:value>PART_COMPARABLE</l:value><l:value>OPERATING_ENVIRONMENT</l:value><l:value>ONCE_CONTROL</l:value><l:value>OBJECT_OWNER</l:value><l:value>OBJECT_CONTROL</l:value><l:value>NUMERIC</l:value><l:value>NONE</l:value><l:value>MUTEX</l:value><l:value>MULTI_ARRAY_LIST</l:value><l:value>MULTAR_LIST_CURSOR</l:value><l:value>MEMORY</l:value><l:value>MEM_INFO</l:value><l:value>MEM_CONST</l:value><l:value>MATH_CONST</l:value><l:value>LIST</l:value><l:value>LINKED_TREE_CURSOR</l:value><l:value>LINKED_TREE</l:value><l:value>LINKED_STACK</l:value><l:value>LINKED_SET</l:value><l:value>LINKED_QUEUE</l:value><l:value>LINKED_PRIORITY_QUEUE</l:value><l:value>LINKED_LIST_CURSOR</l:value><l:value>LINKED_LIST</l:value><l:value>LINKED_CURSOR_TREE</l:value><l:value>LINKED_CIRCULAR</l:value><l:value>LINKABLE</l:value><l:value>LINEAR_ITERATOR</l:value><l:value>LINEAR</l:value><l:value>ITERATOR</l:value><l:value>IO_MEDIUM</l:value><l:value>INTERNAL</l:value><l:value>INTEGER_REF</l:value><l:value>INTEGER_INTERVAL</l:value><l:value>INTEGER</l:value><l:value>INFINITE</l:value><l:value>INDEXABLE</l:value><l:value>IDENTIFIED_CONTROLLER</l:value><l:value>IDENTIFIED</l:value><l:value>HIERARCHICAL</l:value><l:value>HEAP_PRIORITY_QUEUE</l:value><l:value>HASHABLE</l:value><l:value>HASH_TABLE_CURSOR</l:value><l:value>HASH_TABLE</l:value><l:value>GENERAL</l:value><l:value>GC_INFO</l:value><l:value>FUNCTION</l:value><l:value>FORMAT_INTEGER</l:value><l:value>FORMAT_DOUBLE</l:value><l:value>FIXED_TREE</l:value><l:value>FIXED_LIST</l:value><l:value>FIXED</l:value><l:value>FINITE</l:value><l:value>FILE_NAME</l:value><l:value>FILE</l:value><l:value>FIBONACCI</l:value><l:value>EXECUTION_ENVIRONMENT</l:value><l:value>EXCEPTIONS</l:value><l:value>EXCEP_CONST</l:value><l:value>DYNAMIC_TREE</l:value><l:value>DYNAMIC_LIST</l:value><l:value>DYNAMIC_CIRCULAR</l:value><l:value>DYNAMIC_CHAIN</l:value><l:value>DOUBLE_REF</l:value><l:value>DOUBLE_MATH</l:value><l:value>DOUBLE</l:value><l:value>DISPENSER</l:value><l:value>DIRECTORY_NAME</l:value><l:value>DIRECTORY</l:value><l:value>DECLARATOR</l:value><l:value>DEBUG_OUTPUT</l:value><l:value>CURSOR_TREE_ITERATOR</l:value><l:value>CURSOR_TREE</l:value><l:value>CURSOR_STRUCTURE</l:value><l:value>CURSOR</l:value><l:value>COUNTABLE_SEQUENCE</l:value><l:value>COUNTABLE</l:value><l:value>CONTAINER</l:value><l:value>CONSOLE</l:value><l:value>CONDITION_VARIABLE</l:value><l:value>COMPARABLE_STRUCT</l:value><l:value>COMPARABLE_SET</l:value><l:value>COMPARABLE</l:value><l:value>COMPACT_TREE_CURSOR</l:value><l:value>COMPACT_CURSOR_TREE</l:value><l:value>COLLECTION</l:value><l:value>CIRCULAR_CURSOR</l:value><l:value>CIRCULAR</l:value><l:value>CHARACTER_REF</l:value><l:value>CHARACTER</l:value><l:value>CHAIN</l:value><l:value>CELL</l:value><l:value>BOX</l:value><l:value>BOUNDED_STACK</l:value><l:value>BOUNDED_QUEUE</l:value><l:value>BOUNDED</l:value><l:value>BOOLEAN_REF</l:value><l:value>BOOLEAN</l:value><l:value>BOOL_STRING</l:value><l:value>BIT_REF</l:value><l:value>BINARY_TREE</l:value><l:value>BINARY_SEARCH_TREE_SET</l:value><l:value>BINARY_SEARCH_TREE</l:value><l:value>BILINEAR</l:value><l:value>BI_LINKABLE</l:value><l:value>BASIC_ROUTINES</l:value><l:value>BAG</l:value><l:value>ASCII</l:value><l:value>ARRAYED_TREE</l:value><l:value>ARRAYED_STACK</l:value><l:value>ARRAYED_QUEUE</l:value><l:value>ARRAYED_LIST_CURSOR</l:value><l:value>ARRAYED_LIST</l:value><l:value>ARRAYED_CIRCULAR</l:value><l:value>ARRAY2</l:value><l:value>ARRAY</l:value><l:value>ARGUMENTS</l:value><l:value>ANY</l:value><l:value>ACTIVE</l:value></l:set><l:set id="keywords_5" caseSensitive="false"><l:value>yes</l:value><l:value>visible</l:value><l:value>trace</l:value><l:value>system</l:value><l:value>root</l:value><l:value>profile</l:value><l:value>override_cluster</l:value><l:value>object</l:value><l:value>no</l:value><l:value>multithreaded</l:value><l:value>msil_generation_type</l:value><l:value>line_generation</l:value><l:value>library</l:value><l:value>inlining_size</l:value><l:value>inlining</l:value><l:value>include_path</l:value><l:value>il_verifiable</l:value><l:value>exclude</l:value><l:value>exception_trace</l:value><l:value>dynamic_runtime</l:value><l:value>dotnet_naming_convention</l:value><l:value>disabled_debug</l:value><l:value>default</l:value><l:value>debug</l:value><l:value>dead_code_removal</l:value><l:value>console_application</l:value><l:value>cluster</l:value><l:value>cls_compliant</l:value><l:value>check_vape</l:value><l:value>assertion</l:value><l:value>array_optimization</l:value><l:value>all</l:value><l:value>address_expression</l:value></l:set></l:keywords><l:regexps></l:regexps><l:styles><l:style element="splitter_1" color="000060"/><l:style element="comments_1" color="008000" italic="true"/><l:style element="symbols_0" color="600000"/><l:style element="keywords_1" color="0600FF" bold="true"/><l:style element="keywords_2" color="0600FF" bold="true"/><l:style element="keywords_3" color="800080"/><l:style element="keywords_4" color="800000"/><l:style element="keywords_5" color="603000"/><l:style element="string" color="0080A0"/><l:style element="number" color="FF0000"/><l:style element="escaped" color="005070" bold="true"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/m68k.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="m68k" name="Motorola 68000 Assembler" objectOriented="false" escapeChar=""><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>;</l:opening></l:single></l:comments><l:symbols><l:set id="symbols_0"><l:value>,</l:value></l:set></l:symbols><l:quotemarks><l:value>'</l:value><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>adc</l:value><l:value>add</l:value><l:value>ais</l:value><l:value>aix</l:value><l:value>and</l:value><l:value>asl</l:value><l:value>asr</l:value><l:value>bcc</l:value><l:value>bclr</l:value><l:value>bcs</l:value><l:value>beq</l:value><l:value>bge</l:value><l:value>bgt</l:value><l:value>bhcc</l:value><l:value>bhcs</l:value><l:value>bhi</l:value><l:value>bhs</l:value><l:value>bih</l:value><l:value>bil</l:value><l:value>bit</l:value><l:value>ble</l:value><l:value>blo</l:value><l:value>bls</l:value><l:value>blt</l:value><l:value>bmc</l:value><l:value>bmi</l:value><l:value>bms</l:value><l:value>bne</l:value><l:value>bpl</l:value><l:value>bra</l:value><l:value>brclr</l:value><l:value>brn</l:value><l:value>brset</l:value><l:value>bset</l:value><l:value>bsr</l:value><l:value>cbeq</l:value><l:value>clc</l:value><l:value>cli</l:value><l:value>clr</l:value><l:value>cmp</l:value><l:value>com</l:value><l:value>cphx</l:value><l:value>cpx</l:value><l:value>daa</l:value><l:value>dbnz</l:value><l:value>dec</l:value><l:value>div</l:value><l:value>eor</l:value><l:value>inc</l:value><l:value>jmp</l:value><l:value>jsr</l:value><l:value>lda</l:value><l:value>ldhx</l:value><l:value>ldx</l:value><l:value>lsl</l:value><l:value>lsr</l:value><l:value>mov</l:value><l:value>mul</l:value><l:value>neg</l:value><l:value>nop</l:value><l:value>nsa</l:value><l:value>ora</l:value><l:value>psha</l:value><l:value>pshh</l:value><l:value>pshx</l:value><l:value>pula</l:value><l:value>pulh</l:value><l:value>pulx</l:value><l:value>rol</l:value><l:value>ror</l:value><l:value>rsp</l:value><l:value>rti</l:value><l:value>rts</l:value><l:value>sbc</l:value><l:value>sec</l:value><l:value>sei</l:value><l:value>sta</l:value><l:value>sthx</l:value><l:value>stop</l:value><l:value>stx</l:value><l:value>sub</l:value><l:value>swi</l:value><l:value>tap</l:value><l:value>tax</l:value><l:value>tpa</l:value><l:value>tst</l:value><l:value>tsx</l:value><l:value>txa</l:value><l:value>txs</l:value><l:value>wait</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>a</l:value><l:value>h</l:value><l:value>x</l:value><l:value>hx</l:value><l:value>sp</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>#define</l:value><l:value>#endif</l:value><l:value>#else</l:value><l:value>#ifdef</l:value><l:value>#ifndef</l:value><l:value>#include</l:value><l:value>#undef</l:value><l:value>.db</l:value><l:value>.dd</l:value><l:value>.df</l:value><l:value>.dq</l:value><l:value>.dt</l:value><l:value>.dw</l:value><l:value>.end</l:value><l:value>.org</l:value><l:value>equ</l:value></l:set></l:keywords><l:regexps><l:regexp id="regexp_0" value="#?0[0-9a-fA-F]{1,32}[hH]"/><l:regexp id="regexp_1" value="\%[01]{1,64}[bB]"/><l:regexp id="regexp_2" value="^[_a-zA-Z][_a-zA-Z0-9]*?\:"/></l:regexps><l:styles><l:style element="comments_1" color="adadad" italic="true"/><l:style element="symbols_0" color="008000"/><l:style element="keywords_1" color="0000ff" bold="true"/><l:style element="keywords_2" color="0000ff"/><l:style element="keywords_3" color="46aa03" bold="true"/><l:style element="regexp_0" color="22bbff"/><l:style element="regexp_1" color="22bbff"/><l:style element="regexp_2" color="993333"/><l:style element="string" color="7f007f"/><l:style element="number" color="dd22dd"/><l:style element="escaped" color="000099" bold="true"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/cfdg.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="cfdg" name="CFDG" objectOriented="false" escapeChar=""><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>//</l:opening></l:single><l:single id="comments_2"><l:opening>#</l:opening></l:single><l:multiple><l:opening>/*</l:opening><l:closing>*/</l:closing></l:multiple></l:comments><l:symbols><l:set id="symbols_0"><l:value>[</l:value><l:value>]</l:value><l:value>{</l:value><l:value>}</l:value><l:value>*</l:value><l:value>|</l:value></l:set></l:symbols><l:quotemarks><l:value>'</l:value><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>include</l:value><l:value>startshape</l:value><l:value>rule</l:value><l:value>background</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>SQUARE</l:value><l:value>CIRCLE</l:value><l:value>TRIANGLE</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>b</l:value><l:value>brightness</l:value><l:value>h</l:value><l:value>hue</l:value><l:value>sat</l:value><l:value>saturation</l:value><l:value>a</l:value><l:value>alpha</l:value><l:value>x</l:value><l:value>y</l:value><l:value>z</l:value><l:value>s</l:value><l:value>size</l:value><l:value>r</l:value><l:value>rotate</l:value><l:value>f</l:value><l:value>flip</l:value><l:value>skew</l:value><l:value>xml_set_object</l:value></l:set></l:keywords><l:regexps></l:regexps><l:styles><l:style element="comments_1" color="808080" italic="true"/><l:style element="comments_2" color="808080" italic="true"/><l:style element="symbols_0" color="66cc66"/><l:style element="keywords_1" color="717100"/><l:style element="keywords_2" color="000000" bold="true"/><l:style element="keywords_3" color="006666"/><l:style element="comment_multi" color="808080" italic="true"/><l:style element="string" color="ff0000"/><l:style element="number" color="cc66cc"/><l:style element="escaped" color="000099" bold="true"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/robots.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="robots" name="robots.txt" objectOriented="false" escapeChar=""><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>#</l:opening></l:single></l:comments><l:symbols><l:set id="symbols_0"><l:value>:</l:value></l:set></l:symbols><l:quotemarks></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>User-agent</l:value><l:value>Disallow</l:value></l:set></l:keywords><l:regexps></l:regexps><l:styles><l:style element="comments_1" color="808080" italic="true"/><l:style element="symbols_0" color="66cc66"/><l:style element="keywords_1" color="b1b100"/><l:style element="string" color="ff0000"/><l:style element="number" color="cc66cc"/><l:style element="escaped" color="000099" bold="true"/></l:styles></l:language>
