=== cbosdo/coooder/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *   LibreOffice extension for syntax highlighting
 *   Copyright (C) 2008  CÃ©dric Bosdonnat cedric.bosdonnat.ooo@free.fr
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Library General Public
 *   License as published by the Free Software Foundation; 
 *   version 2 of the License.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Library General Public License for more details.
 *
 *   You should have received a copy of the GNU Library General Public
 *   License along with this library; if not, write to the Free
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 -->
<xsd:schema targetNamespace="http://cedric.bosdonnat.free.fr/coooder/language/" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://cedric.bosdonnat.free.fr/coooder/language/">

    <xsd:complexType name="LanguageType">
    	<xsd:sequence>
    		<xsd:element name="objectSplitters" type="SplittersType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="comments" type="CommentsType"></xsd:element>
    		<xsd:element name="symbols" type="SetType"></xsd:element>
    		<xsd:element name="quotemarks" type="ValuesType"></xsd:element>
    		<xsd:element name="hardquotes" type="ValuesType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="hardquoteEscapes" type="ValuesType"
    			minOccurs="0" maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="keywords" type="SetType"></xsd:element>
    		<xsd:element name="regexps" type="RegexpsType"></xsd:element>
    		<xsd:element name="styles" type="StylesType"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="escapeChar" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="objectOriented" type="xsd:boolean" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="language" type="LanguageType"></xsd:element>

    <xsd:complexType name="CommentType" abstract="true">
    	<xsd:sequence>
    		<xsd:element name="opening" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SingleCommentType">
    	<xsd:complexContent>
    		<xsd:extension base="CommentType">
    			<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="MultipleCommentType">
    	<xsd:complexContent>
    		<xsd:extension base="CommentType">
    			<xsd:sequence>
    				<xsd:element name="closing" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    			</xsd:sequence>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="CommentsType">
    	<xsd:sequence>
    		<xsd:element name="single" type="SingleCommentType"
    			minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    		<xsd:element name="multiple" type="MultipleCommentType"
    			minOccurs="0" maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="caseSensitive" type="xsd:boolean" use="optional" default="true"></xsd:attribute>
    </xsd:complexType>
    

    <xsd:complexType name="ValuesType">
    	<xsd:sequence>
    		<xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SplittersType">
    	<xsd:sequence>
    		<xsd:element name="splitter" type="SplitterType" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="SplitterType">
		<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="SetType">
    	<xsd:sequence>
    		<xsd:element name="set" type="SetElementsType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="SetElementsType">
    	<xsd:sequence>
    		<xsd:element name="value" type="xsd:string" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    	<xsd:attribute name="caseSensitive" type="xsd:boolean" default="true" use="optional"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="RegexpsType">
    	<xsd:sequence>
    		<xsd:element name="regexp" type="RegexpType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>



    <xsd:complexType name="RegexpType">
    	<xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    	<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

	<xsd:complexType name="StylesType">
		<xsd:sequence>

			<xsd:element name="style" type="StyleType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	

	<xsd:simpleType name="IdStyleType">
		<xsd:union memberTypes="xsd:IDREF ">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="comment_multi" />
					<xsd:enumeration value="string" />
					<xsd:enumeration value="escaped" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="symbol" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>

    <xsd:complexType name="StyleType">
    	<xsd:attribute name="element" type="IdStyleType"></xsd:attribute>
    	<xsd:attribute name="color" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="bold" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
    	<xsd:attribute name="italic" type="xsd:boolean"  use="optional" default="false"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== cbosdo/coooder/config/org/libreoffice/langs/csharp.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="csharp" name="C#" objectOriented="true" escapeChar="\"><l:objectSplitters><l:splitter id="splitter_1" value="."/><l:splitter id="splitter_2" value="::"/></l:objectSplitters><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>//</l:opening></l:single><l:single id="comments_2"><l:opening>#</l:opening></l:single><l:multiple><l:opening>/*</l:opening><l:closing>*/</l:closing></l:multiple></l:comments><l:symbols><l:set id="symbols_0"><l:value>+</l:value><l:value>-</l:value><l:value>*</l:value><l:value>?</l:value><l:value>=</l:value><l:value>/</l:value><l:value>%</l:value><l:value>&amp;</l:value><l:value>&gt;</l:value><l:value>&lt;</l:value><l:value>^</l:value><l:value>!</l:value><l:value>:</l:value><l:value>;</l:value><l:value>(</l:value><l:value>)</l:value><l:value>{</l:value><l:value>}</l:value><l:value>[</l:value><l:value>]</l:value><l:value>|</l:value></l:set></l:symbols><l:quotemarks><l:value>'</l:value><l:value>&quot;</l:value></l:quotemarks><l:hardquotes><l:value>@&quot;</l:value><l:value>&quot;</l:value></l:hardquotes><l:hardquoteEscapes><l:value>&quot;&quot;</l:value></l:hardquoteEscapes><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>as</l:value><l:value>auto</l:value><l:value>base</l:value><l:value>break</l:value><l:value>case</l:value><l:value>catch</l:value><l:value>const</l:value><l:value>continue</l:value><l:value>default</l:value><l:value>do</l:value><l:value>else</l:value><l:value>event</l:value><l:value>explicit</l:value><l:value>extern</l:value><l:value>false</l:value><l:value>finally</l:value><l:value>fixed</l:value><l:value>for</l:value><l:value>foreach</l:value><l:value>goto</l:value><l:value>if</l:value><l:value>implicit</l:value><l:value>in</l:value><l:value>internal</l:value><l:value>lock</l:value><l:value>namespace</l:value><l:value>null</l:value><l:value>operator</l:value><l:value>out</l:value><l:value>override</l:value><l:value>params</l:value><l:value>private</l:value><l:value>protected</l:value><l:value>public</l:value><l:value>readonly</l:value><l:value>ref</l:value><l:value>return</l:value><l:value>sealed</l:value><l:value>stackalloc</l:value><l:value>static</l:value><l:value>switch</l:value><l:value>this</l:value><l:value>throw</l:value><l:value>true</l:value><l:value>try</l:value><l:value>unsafe</l:value><l:value>using</l:value><l:value>virtual</l:value><l:value>void</l:value><l:value>while</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>#elif</l:value><l:value>#endif</l:value><l:value>#endregion</l:value><l:value>#else</l:value><l:value>#error</l:value><l:value>#define</l:value><l:value>#if</l:value><l:value>#line</l:value><l:value>#region</l:value><l:value>#undef</l:value><l:value>#warning</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>checked</l:value><l:value>is</l:value><l:value>new</l:value><l:value>sizeof</l:value><l:value>typeof</l:value><l:value>unchecked</l:value></l:set><l:set id="keywords_4" caseSensitive="false"><l:value>bool</l:value><l:value>byte</l:value><l:value>char</l:value><l:value>class</l:value><l:value>decimal</l:value><l:value>delegate</l:value><l:value>double</l:value><l:value>enum</l:value><l:value>float</l:value><l:value>int</l:value><l:value>interface</l:value><l:value>long</l:value><l:value>object</l:value><l:value>sbyte</l:value><l:value>short</l:value><l:value>string</l:value><l:value>struct</l:value><l:value>uint</l:value><l:value>ulong</l:value><l:value>ushort</l:value></l:set><l:set id="keywords_5" caseSensitive="false"><l:value>Microsoft.Win32</l:value><l:value>System</l:value><l:value>System.CodeDOM</l:value><l:value>System.CodeDOM.Compiler</l:value><l:value>System.Collections</l:value><l:value>System.Collections.Bases</l:value><l:value>System.ComponentModel</l:value><l:value>System.ComponentModel.Design</l:value><l:value>System.ComponentModel.Design.CodeModel</l:value><l:value>System.Configuration</l:value><l:value>System.Configuration.Assemblies</l:value><l:value>System.Configuration.Core</l:value><l:value>System.Configuration.Install</l:value><l:value>System.Configuration.Interceptors</l:value><l:value>System.Configuration.Schema</l:value><l:value>System.Configuration.Web</l:value><l:value>System.Core</l:value><l:value>System.Data</l:value><l:value>System.Data.ADO</l:value><l:value>System.Data.Design</l:value><l:value>System.Data.Internal</l:value><l:value>System.Data.SQL</l:value><l:value>System.Data.SQLTypes</l:value><l:value>System.Data.XML</l:value><l:value>System.Data.XML.DOM</l:value><l:value>System.Data.XML.XPath</l:value><l:value>System.Data.XML.XSLT</l:value><l:value>System.Diagnostics</l:value><l:value>System.Diagnostics.SymbolStore</l:value><l:value>System.DirectoryServices</l:value><l:value>System.Drawing</l:value><l:value>System.Drawing.Design</l:value><l:value>System.Drawing.Drawing2D</l:value><l:value>System.Drawing.Imaging</l:value><l:value>System.Drawing.Printing</l:value><l:value>System.Drawing.Text</l:value><l:value>System.Globalization</l:value><l:value>System.IO</l:value><l:value>System.IO.IsolatedStorage</l:value><l:value>System.Messaging</l:value><l:value>System.Net</l:value><l:value>System.Net.Sockets</l:value><l:value>System.NewXml</l:value><l:value>System.NewXml.XPath</l:value><l:value>System.NewXml.Xsl</l:value><l:value>System.Reflection</l:value><l:value>System.Reflection.Emit</l:value><l:value>System.Resources</l:value><l:value>System.Runtime.InteropServices</l:value><l:value>System.Runtime.InteropServices.Expando</l:value><l:value>System.Runtime.Remoting</l:value><l:value>System.Runtime.Serialization</l:value><l:value>System.Runtime.Serialization.Formatters</l:value><l:value>System.Runtime.Serialization.Formatters.Binary</l:value><l:value>System.Security</l:value><l:value>System.Security.Cryptography</l:value><l:value>System.Security.Cryptography.X509Certificates</l:value><l:value>System.Security.Permissions</l:value><l:value>System.Security.Policy</l:value><l:value>System.Security.Principal</l:value><l:value>System.ServiceProcess</l:value><l:value>System.Text</l:value><l:value>System.Text.RegularExpressions</l:value><l:value>System.Threading</l:value><l:value>System.Timers</l:value><l:value>System.Web</l:value><l:value>System.Web.Caching</l:value><l:value>System.Web.Configuration</l:value><l:value>System.Web.Security</l:value><l:value>System.Web.Services</l:value><l:value>System.Web.Services.Description</l:value><l:value>System.Web.Services.Discovery</l:value><l:value>System.Web.Services.Protocols</l:value><l:value>System.Web.UI</l:value><l:value>System.Web.UI.Design</l:value><l:value>System.Web.UI.Design.WebControls</l:value><l:value>System.Web.UI.Design.WebControls.ListControls</l:value><l:value>System.Web.UI.HtmlControls</l:value><l:value>System.Web.UI.WebControls</l:value><l:value>System.WinForms</l:value><l:value>System.WinForms.ComponentModel</l:value><l:value>System.WinForms.Design</l:value><l:value>System.Xml</l:value><l:value>System.Xml.Serialization</l:value><l:value>System.Xml.Serialization.Code</l:value><l:value>System.Xml.Serialization.Schema</l:value></l:set></l:keywords><l:regexps></l:regexps><l:styles><l:style element="splitter_1" color="0000FF"/><l:style element="splitter_2" color="0000FF"/><l:style element="comments_1" color="008080" italic="true"/><l:style element="comments_2" color="008080"/><l:style element="symbols_0" color="008000"/><l:style element="keywords_1" color="0600FF"/><l:style element="keywords_2" color="FF8000" bold="true"/><l:style element="keywords_3" color="008000"/><l:style element="keywords_4" color="FF0000"/><l:style element="keywords_5" color="000000"/><l:style element="comment_multi" color="008080" italic="true"/><l:style element="string" color="666666"/><l:style element="number" color="FF0000"/><l:style element="escaped" color="008080" bold="true"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/vhdl.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="vhdl" name="VHDL" objectOriented="false" escapeChar=""><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>--</l:opening></l:single><l:multiple><l:opening>%</l:opening><l:closing>%</l:closing></l:multiple></l:comments><l:symbols><l:set id="symbols_0"><l:value>[</l:value><l:value>]</l:value><l:value>(</l:value><l:value>)</l:value><l:value>;</l:value><l:value>:</l:value><l:value>&lt;</l:value><l:value>&gt;</l:value><l:value>=</l:value><l:value>&lt;=</l:value><l:value>:=</l:value><l:value>=&gt;</l:value><l:value>==</l:value></l:set></l:symbols><l:quotemarks><l:value>&quot;</l:value></l:quotemarks><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>access</l:value><l:value>after</l:value><l:value>alias</l:value><l:value>all</l:value><l:value>assert</l:value><l:value>attribute</l:value><l:value>architecture</l:value><l:value>begin</l:value><l:value>block</l:value><l:value>body</l:value><l:value>buffer</l:value><l:value>bus</l:value><l:value>case</l:value><l:value>component</l:value><l:value>configuration</l:value><l:value>constant</l:value><l:value>disconnect</l:value><l:value>downto</l:value><l:value>else</l:value><l:value>elsif</l:value><l:value>end</l:value><l:value>entity</l:value><l:value>exit</l:value><l:value>file</l:value><l:value>for</l:value><l:value>function</l:value><l:value>generate</l:value><l:value>generic</l:value><l:value>group</l:value><l:value>guarded</l:value><l:value>if</l:value><l:value>impure</l:value><l:value>in</l:value><l:value>inertial</l:value><l:value>inout</l:value><l:value>is</l:value><l:value>label</l:value><l:value>library</l:value><l:value>linkage</l:value><l:value>literal</l:value><l:value>loop</l:value><l:value>map</l:value><l:value>new</l:value><l:value>next</l:value><l:value>null</l:value><l:value>of</l:value><l:value>on</l:value><l:value>open</l:value><l:value>others</l:value><l:value>out</l:value><l:value>package</l:value><l:value>port</l:value><l:value>postponed</l:value><l:value>procedure</l:value><l:value>process</l:value><l:value>pure</l:value><l:value>range</l:value><l:value>record</l:value><l:value>register</l:value><l:value>reject</l:value><l:value>report</l:value><l:value>return</l:value><l:value>select</l:value><l:value>severity</l:value><l:value>signal</l:value><l:value>shared</l:value><l:value>subtype</l:value><l:value>then</l:value><l:value>to</l:value><l:value>transport</l:value><l:value>type</l:value><l:value>unaffected</l:value><l:value>units</l:value><l:value>until</l:value><l:value>use</l:value><l:value>variable</l:value><l:value>wait</l:value><l:value>when</l:value><l:value>while</l:value><l:value>with</l:value><l:value>note</l:value><l:value>warning</l:value><l:value>error</l:value><l:value>failure</l:value><l:value>and</l:value><l:value>or</l:value><l:value>xor</l:value><l:value>not</l:value><l:value>nor</l:value><l:value>used</l:value><l:value>memory</l:value><l:value>segments</l:value><l:value>dff</l:value><l:value>dffe</l:value><l:value>help_id</l:value><l:value>mod</l:value><l:value>info</l:value><l:value>latch</l:value><l:value>rising_edge</l:value><l:value>falling_edge</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>bit</l:value><l:value>bit_vector</l:value><l:value>character</l:value><l:value>boolean</l:value><l:value>integer</l:value><l:value>real</l:value><l:value>time</l:value><l:value>string</l:value><l:value>severity_level</l:value><l:value>positive</l:value><l:value>natural</l:value><l:value>signed</l:value><l:value>unsigned</l:value><l:value>line</l:value><l:value>text</l:value><l:value>std_logic</l:value><l:value>std_logic_vector</l:value><l:value>std_ulogic</l:value><l:value>std_ulogic_vector</l:value><l:value>qsim_state</l:value><l:value>qsim_state_vector</l:value><l:value>qsim_12state</l:value><l:value>qsim_12state_vector</l:value><l:value>qsim_strength</l:value><l:value>mux_bit</l:value><l:value>mux_vector</l:value><l:value>reg_bit</l:value><l:value>reg_vector</l:value><l:value>wor_bit</l:value><l:value>wor_vector</l:value><l:value>work</l:value><l:value>ieee</l:value><l:value>std_logic_signed</l:value><l:value>std_logic_1164</l:value><l:value>std_logic_arith</l:value><l:value>numeric_std</l:value></l:set></l:keywords><l:regexps><l:regexp id="regexp_0" value="(\b0x[0-9a-fA-F]+|\b\d[0-9a-fA-F]+[hH])|(\b\d+?(\.\d+?)?E[+\-]?\d+)|(\bns)|('[0-9a-zA-Z]+(?!'))"/><l:regexp id="regexp_1" value="\b(''\d'')"/></l:regexps><l:styles><l:style element="comments_1" color="008000" italic="true"/><l:style element="symbols_0" color="000066"/><l:style element="keywords_1" color="000080" bold="true"/><l:style element="keywords_2" color="0000ff"/><l:style element="regexp_0" color="ff0000"/><l:style element="regexp_1" color="ff0000"/><l:style element="comment_multi" color="008000" italic="true"/><l:style element="string" color="7f007f"/><l:style element="number" color="ff0000"/><l:style element="escaped" color="000099" bold="true"/></l:styles></l:language>

=== cbosdo/coooder/config/org/libreoffice/langs/perl.xml
<?xml version="1.0" encoding="UTF-8"?>
<l:language xmlns:l="http://cedric.bosdonnat.free.fr/coooder/language/"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:schemaLocation="http://cedric.bosdonnat.free.fr/coooder/language/ language.xsd " 	id="perl" name="Perl" objectOriented="true" escapeChar="\"><l:objectSplitters><l:splitter id="splitter_1" value="-&amp;gt;"/><l:splitter id="splitter_2" value="::"/></l:objectSplitters><l:comments caseSensitive="false"><l:single id="comments_1"><l:opening>#</l:opening></l:single><l:multiple><l:opening>=back</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=head</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=item</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=over</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=begin</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=end</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=for</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=encoding</l:opening><l:closing>=cut</l:closing></l:multiple><l:multiple><l:opening>=pod</l:opening><l:closing>=cut</l:closing></l:multiple></l:comments><l:symbols><l:set id="symbols_0"><l:value>&lt;</l:value><l:value>&gt;</l:value><l:value>=</l:value><l:value>!</l:value><l:value>@</l:value><l:value>~</l:value><l:value>&amp;</l:value><l:value>|</l:value><l:value>+</l:value><l:value>-</l:value><l:value>*</l:value><l:value>/</l:value><l:value>%</l:value><l:value>,</l:value><l:value>;</l:value><l:value>?</l:value><l:value>:</l:value></l:set></l:symbols><l:quotemarks><l:value>&quot;</l:value><l:value>`</l:value></l:quotemarks><l:hardquotes><l:value>'</l:value><l:value>'</l:value></l:hardquotes><l:hardquoteEscapes><l:value>\'</l:value></l:hardquoteEscapes><l:keywords><l:set id="keywords_1" caseSensitive="false"><l:value>case</l:value><l:value>do</l:value><l:value>else</l:value><l:value>elsif</l:value><l:value>for</l:value><l:value>if</l:value><l:value>then</l:value><l:value>until</l:value><l:value>while</l:value><l:value>foreach</l:value><l:value>my</l:value><l:value>or</l:value><l:value>and</l:value><l:value>unless</l:value><l:value>next</l:value><l:value>last</l:value><l:value>redo</l:value><l:value>not</l:value><l:value>our</l:value><l:value>reset</l:value><l:value>continue</l:value><l:value>and</l:value><l:value>cmp</l:value><l:value>ne</l:value></l:set><l:set id="keywords_2" caseSensitive="false"><l:value>use</l:value><l:value>sub</l:value><l:value>new</l:value><l:value>__END__</l:value><l:value>__DATA__</l:value><l:value>__DIE__</l:value><l:value>__WARN__</l:value><l:value>BEGIN</l:value><l:value>STDIN</l:value><l:value>STDOUT</l:value><l:value>STDERR</l:value></l:set><l:set id="keywords_3" caseSensitive="false"><l:value>abs</l:value><l:value>accept</l:value><l:value>alarm</l:value><l:value>atan2</l:value><l:value>bind</l:value><l:value>binmode</l:value><l:value>bless</l:value><l:value>caller</l:value><l:value>chdir</l:value><l:value>chmod</l:value><l:value>chomp</l:value><l:value>chop</l:value><l:value>chown</l:value><l:value>chr</l:value><l:value>chroot</l:value><l:value>close</l:value><l:value>closedir</l:value><l:value>connect</l:value><l:value>continue</l:value><l:value>cos</l:value><l:value>crypt</l:value><l:value>dbmclose</l:value><l:value>dbmopen</l:value><l:value>defined</l:value><l:value>delete</l:value><l:value>die</l:value><l:value>dump</l:value><l:value>each</l:value><l:value>endgrent</l:value><l:value>endhostent</l:value><l:value>endnetent</l:value><l:value>endprotoent</l:value><l:value>endpwent</l:value><l:value>endservent</l:value><l:value>eof</l:value><l:value>eval</l:value><l:value>exec</l:value><l:value>exists</l:value><l:value>exit</l:value><l:value>exp</l:value><l:value>fcntl</l:value><l:value>fileno</l:value><l:value>flock</l:value><l:value>fork</l:value><l:value>format</l:value><l:value>formline</l:value><l:value>getc</l:value><l:value>getgrent</l:value><l:value>getgrgid</l:value><l:value>getgrnam</l:value><l:value>gethostbyaddr</l:value><l:value>gethostbyname</l:value><l:value>gethostent</l:value><l:value>getlogin</l:value><l:value>getnetbyaddr</l:value><l:value>getnetbyname</l:value><l:value>getnetent</l:value><l:value>getpeername</l:value><l:value>getpgrp</l:value><l:value>getppid</l:value><l:value>getpriority</l:value><l:value>getprotobyname</l:value><l:value>getprotobynumber</l:value><l:value>getprotoent</l:value><l:value>getpwent</l:value><l:value>getpwnam</l:value><l:value>getpwuid</l:value><l:value>getservbyname</l:value><l:value>getservbyport</l:value><l:value>getservent</l:value><l:value>getsockname</l:value><l:value>getsockopt</l:value><l:value>glob</l:value><l:value>gmtime</l:value><l:value>goto</l:value><l:value>grep</l:value><l:value>hex</l:value><l:value>import</l:value><l:value>index</l:value><l:value>int</l:value><l:value>ioctl</l:value><l:value>join</l:value><l:value>keys</l:value><l:value>kill</l:value><l:value>last</l:value><l:value>lc</l:value><l:value>lcfirst</l:value><l:value>length</l:value><l:value>link</l:value><l:value>listen</l:value><l:value>local</l:value><l:value>localtime</l:value><l:value>log</l:value><l:value>lstat</l:value><l:value>m</l:value><l:value>map</l:value><l:value>mkdir</l:value><l:value>msgctl</l:value><l:value>msgget</l:value><l:value>msgrcv</l:value><l:value>msgsnd</l:value><l:value>my</l:value><l:value>next</l:value><l:value>no</l:value><l:value>oct</l:value><l:value>open</l:value><l:value>opendir</l:value><l:value>ord</l:value><l:value>our</l:value><l:value>pack</l:value><l:value>package</l:value><l:value>pipe</l:value><l:value>pop</l:value><l:value>pos</l:value><l:value>print</l:value><l:value>printf</l:value><l:value>prototype</l:value><l:value>push</l:value><l:value>qq</l:value><l:value>qr</l:value><l:value>quotemeta</l:value><l:value>qw</l:value><l:value>qx</l:value><l:value>q</l:value><l:value>rand</l:value><l:value>read</l:value><l:value>readdir</l:value><l:value>readline</l:value><l:value>readlink</l:value><l:value>readpipe</l:value><l:value>recv</l:value><l:value>redo</l:value><l:value>ref</l:value><l:value>rename</l:value><l:value>require</l:value><l:value>return</l:value><l:value>reverse</l:value><l:value>rewinddir</l:value><l:value>rindex</l:value><l:value>rmdir</l:value><l:value>s</l:value><l:value>scalar</l:value><l:value>seek</l:value><l:value>seekdir</l:value><l:value>select</l:value><l:value>semctl</l:value><l:value>semget</l:value><l:value>semop</l:value><l:value>send</l:value><l:value>setgrent</l:value><l:value>sethostent</l:value><l:value>setnetent</l:value><l:value>setpgrp</l:value><l:value>setpriority</l:value><l:value>setprotoent</l:value><l:value>setpwent</l:value><l:value>setservent</l:value><l:value>setsockopt</l:value><l:value>shift</l:value><l:value>shmctl</l:value><l:value>shmget</l:value><l:value>shmread</l:value><l:value>shmwrite</l:value><l:value>shutdown</l:value><l:value>sin</l:value><l:value>sleep</l:value><l:value>socket</l:value><l:value>socketpair</l:value><l:value>sort</l:value><l:value>splice</l:value><l:value>split</l:value><l:value>sprintf</l:value><l:value>sqrt</l:value><l:value>srand</l:value><l:value>stat</l:value><l:value>study</l:value><l:value>substr</l:value><l:value>symlink</l:value><l:value>syscall</l:value><l:value>sysopen</l:value><l:value>sysread</l:value><l:value>sysseek</l:value><l:value>system</l:value><l:value>syswrite</l:value><l:value>tell</l:value><l:value>telldir</l:value><l:value>tie</l:value><l:value>tied</l:value><l:value>time</l:value><l:value>times</l:value><l:value>tr</l:value><l:value>truncate</l:value><l:value>uc</l:value><l:value>ucfirst</l:value><l:value>umask</l:value><l:value>undef</l:value><l:value>unlink</l:value><l:value>unpack</l:value><l:value>unshift</l:value><l:value>untie</l:value><l:value>utime</l:value><l:value>values</l:value><l:value>vec</l:value><l:value>wait</l:value><l:value>waitpid</l:value><l:value>wantarray</l:value><l:value>warn</l:value><l:value>write</l:value><l:value>y</l:value></l:set></l:keywords><l:regexps><l:regexp id="regexp_0" value="[\$%@]+[a-zA-Z_][a-zA-Z0-9_]*"/><l:regexp id="regexp_4" value="&amp;lt;[a-zA-Z_][a-zA-Z0-9_]*&amp;gt;"/></l:regexps><l:styles><l:style element="splitter_1" color="006600"/><l:style element="splitter_2" color="006600"/><l:style element="comments_1" color="666666" italic="true"/><l:style element="symbols_0" color="339933"/><l:style element="keywords_1" color="b1b100"/><l:style element="keywords_2" color="000000" bold="true"/><l:style element="keywords_3" color="000066"/><l:style element="regexp_0" color="0000ff"/><l:style element="regexp_4" color="009999"/><l:style element="comment_multi" color="666666" italic="true"/><l:style element="string" color="ff0000"/><l:style element="number" color="cc66cc"/><l:style element="escaped" color="000099" bold="true"/></l:styles></l:language>
